mes = {'update_id': 895937467,
 'message': {'message_id': 19033, 'date': 1618345328,
             'chat': {'id': -1001165785711, 'type': 'supergroup', 'title': '🅐🅝🅤🅢 - беспредел пипидино'},
             'text': '/say Вартас молодец', 'entities':
                 [{'type': 'bot_command', 'offset': 0, 'length': 4},
                  {'type': 'text_mention', 'offset': 5, 'length': 6, 'user': {'id': 1346238115, 'first_name': 'Vartas', 'is_bot': False}}],
             'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False,
             'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False,
             'from': {'id': 52351769, 'first_name': 'Andrey', 'is_bot': False, 'last_name': 'Burmistrov', 'username': 'aburmistrov', 'language_code': 'ru'}}}





private = {'id': 52351769, 'type': 'private', 'title': None, 'username': 'aburmistrov', 'first_name': 'Andrey',
           'last_name': 'Burmistrov',
           'photo': {'small_file_id': 'AQADAgADt6cxGxnTHgMACQ2DKgAEAgADGdMeAwAE4ea1OK4VaCV41gEAAR4E',
                     'small_file_unique_id': 'AQAEDYMqAAR41gEAAQ',
                     'big_file_id': 'AQADAgADt6cxGxnTHgMACQ2DKgAEAwADGdMeAwAE4ea1OK4VaCV61gEAAR4E',
                     'big_file_unique_id': 'AQAEDYMqAAR61gEAAQ'}, 'bio': None, 'description': None,
           'invite_link': None, 'pinned_message': None, 'permissions': None, 'slow_mode_delay': None,
           'sticker_set_name': None,
           'can_set_sticker_set': None, 'linked_chat_id': None, 'location': None}

chat = {'id': -1001165785711, 'type': 'supergroup', 'title': '🅐🅝🅤🅢 - беспредел пипидино', 'username': None,
        'first_name': None, 'last_name': None,
        'photo': {'small_file_id': 'AQADAgATNR8imy4AAwIAA5F13uUW____s5iYCA7I0kHtSwMAAR4E',
                  'small_file_unique_id': 'AQADNR8imy4AA-1LAwAB',
                  'big_file_id': 'AQADAgATNR8imy4AAwMAA5F13uUW____s5iYCA7I0kHvSwMAAR4E',
                  'big_file_unique_id': 'AQADNR8imy4AA-9LAwAB'}, 'bio': None, 'description': None,
        'invite_link': 'https://t.me/joinchat/VDeyY7m4JtAxOGYy',
        'pinned_message': None,
        'permissions': None, 'slow_mode_delay': 3600,
        'sticker_set_name': None,
        'can_set_sticker_set': None, 'linked_chat_id': None, 'location': None}
###########################

{'content_type': 'text', 'id': 16953, 'message_id': 16953,
 'from_user': {'id': 52351769, 'is_bot': False, 'first_name': 'Andrey', 'username': 'aburmistrov',
               'last_name': 'Burmistrov', 'language_code': 'ru', 'can_join_groups': None,
               'can_read_all_group_messages': None, 'supports_inline_queries': None}, 'date': 1616950940,
 'chat': {'id': -1001165785711, 'type': 'supergroup', 'title': '🅐🅝🅤🅢 - беспредел пипидино', 'username': None,
          'first_name': None, 'last_name': None, 'photo': None, 'bio': None, 'description': None, 'invite_link': None,
          'pinned_message': None, 'permissions': None, 'slow_mode_delay': None, 'sticker_set_name': None,
          'can_set_sticker_set': None, 'linked_chat_id': None, 'location': None}, 'forward_from': None,
 'forward_from_chat': None, 'forward_from_message_id': None, 'forward_signature': None, 'forward_sender_name': None,
 'forward_date': None, 'reply_to_message': None, 'edit_date': None, 'media_group_id': None, 'author_signature': None,
 'text': 'Вартас пёс (тест)',
 'entities': [ < telebot.types.MessageEntity object at 0x000001E6694EBD60 >], 'caption_entities': None, 'audio': None, 'document': None, 'photo': None, 'sticker': None, 'video': None, 'video_note': None, 'voice': None, 'caption': None, 'contact': None, 'location': None, 'venue': None, 'animation': None, 'dice': None, 'new_chat_member': None, 'new_chat_members': None, 'left_chat_member': None, 'new_chat_title': None, 'new_chat_photo': None, 'delete_chat_photo': None, 'group_chat_created': None, 'supergroup_chat_created': None, 'channel_chat_created': None, 'migrate_to_chat_id': None, 'migrate_from_chat_id': None, 'pinned_message': None, 'invoice': None, 'successful_payment': None, 'connected_website': None, 'reply_markup': None, 'json': {
    'message_id': 16953, 'from': {'id': 52351769, 'is_bot': False, 'first_name': 'Andrey', 'last_name': 'Burmistrov',
                                  'username': 'aburmistrov', 'language_code': 'ru'},
    'chat': {'id': -1001165785711, 'title': '🅐🅝🅤🅢 - беспредел пипидино', 'type': 'supergroup'}, 'date': 1616950940,
    'text': 'Вартас пёс (тест)', 'entities': [{'offset': 0, 'length': 6, 'type': 'text_mention',
                                               'user': {'id': 1346238115, 'is_bot': False, 'first_name': 'Vartas'}}]}}


##########################
user = {'user': {'id': 1775365464, 'is_bot': True, 'first_name': 'megalohobot', 'username': 'megalohobot',
                 'last_name': None,
                 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': None,
        'can_be_edited': False,
        'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
        'can_promote_members': False, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
        'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
        'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 889248, 'is_bot': False, 'first_name': 'Karkyshka', 'username': 'Karkyshka', 'last_name': None,
                 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': None,
        'can_be_edited': False,
        'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
        'can_promote_members': False, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
        'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
        'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 1577503305, 'is_bot': False, 'first_name': 'Zeborka', 'username': None, 'last_name': 'Zeborka',
                 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': None,
        'can_be_edited': False,
        'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
        'can_promote_members': True, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
        'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
        'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {
    'user': {'id': 1057783333, 'is_bot': False, 'first_name': 'Ush', 'username': 'A_Ushakoff', 'last_name': 'Aleksey',
             'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
             'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': 'Админ',
    'can_be_edited': False,
    'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
    'can_promote_members': True, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
    'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
    'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 1560745599, 'is_bot': False, 'first_name': 'Иван', 'username': None, 'last_name': 'Аккуратов',
                 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': 'Burning Man',
        'can_be_edited': False, 'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True,
        'can_restrict_members': True, 'can_promote_members': True, 'can_change_info': True, 'can_invite_users': True,
        'can_pin_messages': True, 'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None,
        'can_send_polls': None, 'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 1539854471, 'is_bot': False, 'first_name': 'Maxim', 'username': None, 'last_name': None,
                 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': 'Шарик',
        'can_be_edited': False,
        'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
        'can_promote_members': True, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
        'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
        'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 1599686606, 'is_bot': False, 'first_name': 'Андрей', 'username': None, 'last_name': None,
                 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': 'Архивариус',
        'can_be_edited': False, 'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True,
        'can_restrict_members': True, 'can_promote_members': False, 'can_change_info': True, 'can_invite_users': True,
        'can_pin_messages': True, 'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None,
        'can_send_polls': None, 'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 1586530719, 'is_bot': False, 'first_name': 'Evgeniy', 'username': None, 'last_name': None,
                 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': None,
        'can_be_edited': False,
        'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
        'can_promote_members': False, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
        'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
        'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 747091323, 'is_bot': False, 'first_name': 'Светлана', 'username': None, 'last_name': None,
                 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': None,
        'can_be_edited': False,
        'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
        'can_promote_members': True, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
        'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
        'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 742508167, 'is_bot': False, 'first_name': '83ND3R', 'username': None, 'last_name': None,
                 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': None,
        'can_be_edited': False,
        'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
        'can_promote_members': True, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
        'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
        'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 535078107, 'is_bot': False, 'first_name': 'Оксана', 'username': 'Coffeewithoutmilk',
                 'last_name': None,
                 'language_code': 'ru', 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': 'Хомяк',
        'can_be_edited': False,
        'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
        'can_promote_members': True, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
        'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
        'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 993222503, 'is_bot': False, 'first_name': 'DARYAL', 'username': None, 'last_name': None,
                 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': None,
        'can_be_edited': False,
        'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
        'can_promote_members': False, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
        'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
        'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 1346238115, 'is_bot': False, 'first_name': 'Vartas', 'username': None, 'last_name': None,
                 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': 'Пёс',
        'can_be_edited': False,
        'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
        'can_promote_members': True, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
        'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
        'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 437258746, 'is_bot': False, 'first_name': 'Eva', 'username': None, 'last_name': None,
                 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': None,
        'can_be_edited': False,
        'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
        'can_promote_members': False, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
        'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
        'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 364642280, 'is_bot': False, 'first_name': 'lera', 'username': None, 'last_name': None,
                 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': None,
        'can_be_edited': False,
        'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
        'can_promote_members': False, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
        'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
        'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {
    'user': {'id': 442181816, 'is_bot': False, 'first_name': 'Alexandr', 'username': None, 'last_name': 'Gorodnichev',
             'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
             'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': None, 'can_be_edited': False,
    'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
    'can_promote_members': True, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
    'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
    'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 240470046, 'is_bot': False, 'first_name': 'Maxx', 'username': 'pub_maxx', 'last_name': None,
                 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': None,
        'can_be_edited': False,
        'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
        'can_promote_members': True, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
        'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
        'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 375423828, 'is_bot': False, 'first_name': 'A', 'username': None, 'last_name': 'Ush',
                 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': None,
        'can_be_edited': False,
        'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
        'can_promote_members': True, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
        'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
        'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 312779364, 'is_bot': False, 'first_name': 'Morbo', 'username': None, 'last_name': 'Morbo',
                 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': None,
        'can_be_edited': False,
        'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
        'can_promote_members': True, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
        'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
        'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {
    'user': {'id': 274448416, 'is_bot': False, 'first_name': 'Boris', 'username': 'Bobrobelka', 'last_name': 'Pavlov',
             'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
             'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': None, 'can_be_edited': False,
    'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
    'can_promote_members': True, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
    'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
    'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 199361131, 'is_bot': False, 'first_name': 'Aleksey', 'username': 'AlekseyLopatin',
                 'last_name': 'Lopatin', 'language_code': None, 'can_join_groups': None,
                 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': None,
        'can_be_edited': False,
        'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
        'can_promote_members': True, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
        'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
        'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 129079647, 'is_bot': False, 'first_name': 'РыБо', 'username': None, 'last_name': 'РыБо',
                 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': None,
        'can_be_edited': False,
        'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
        'can_promote_members': True, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
        'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
        'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 64094289, 'is_bot': False, 'first_name': 'slalus', 'username': 'slalus', 'last_name': None,
                 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': 'Mr.Breaking news',
        'can_be_edited': False, 'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True,
        'can_restrict_members': True, 'can_promote_members': True, 'can_change_info': True, 'can_invite_users': True,
        'can_pin_messages': True, 'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None,
        'can_send_polls': None, 'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 52351769, 'is_bot': False, 'first_name': 'Andrey', 'username': 'aburmistrov',
                 'last_name': 'Burmistrov',
                 'language_code': 'ru', 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'creator', 'custom_title': None, 'can_be_edited': None,
        'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': None, 'can_restrict_members': None,
        'can_promote_members': None, 'can_change_info': None, 'can_invite_users': None, 'can_pin_messages': None,
        'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
        'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
user = {'user': {'id': 5577509, 'is_bot': False, 'first_name': 'Da Tek Shaman', 'username': 'DaTekShaman',
                 'last_name': None,
                 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None,
                 'supports_inline_queries': None}, 'status': 'administrator', 'custom_title': None,
        'can_be_edited': False,
        'can_post_messages': None, 'can_edit_messages': None, 'can_delete_messages': True, 'can_restrict_members': True,
        'can_promote_members': True, 'can_change_info': True, 'can_invite_users': True, 'can_pin_messages': True,
        'is_member': None, 'can_send_messages': None, 'can_send_media_messages': None, 'can_send_polls': None,
        'can_send_other_messages': None, 'can_add_web_page_previews': None, 'until_date': None}
